### Variables 
@apiurl = http://127.0.0.1:8000/api/address

### GET all address
GET {{apiurl}} HTTP/1.1

### POST cria address
POST {{apiurl}} HTTP/1.1
Content-Type: application/json

{
  "state": "Santa Catarina",
  "city": "Rio Negro",
  "neighborhood": "Centro",
  "street": "Rua Tenente Ary Rauen",
  "number": "123"
}

### PUT atualiza o address pelo id
PUT {{apiurl}}/1 HTTP/1.1
Content-Type: application/json

{
  "state": "Santa Catarina",
  "city": "Rio Negro",
  "neighborhood": "Centro",
  "street": "Rua Tenente Ary Rauen",
  "number": "124"
}

### DELETE deleta o address pelo id
GET {{apiurl}}/1 HTTP/1.1
Content-Type: application/json