### Variables 
@apiurl = http://127.0.0.1:8000/api/studying

### GET all studying
GET {{apiurl}} HTTP/1.1

### POST cria studying
POST {{apiurl}} HTTP/1.1
Content-Type: application/json

{
  "student_id": 1,
  "course_id": 3,
  "institution_id": 1,
  "beginning": "2022-08-01",
  "end": "2026-06-30",
  "semester": "2",
  "period": "noturno"
}

### GET pega studying pelo id
GET {{apiurl}}/1 HTTP/1.1
Content-Type: application/json

### PUT atualiza o studying pelo id
PUT {{apiurl}}/1 HTTP/1.1
Content-Type: application/json

{
  "student_id": 1, 
  "course_id": 3,
  "institution_id": 1,
  "beginning": "2023-02-01",
  "end": "2026-12-15",
  "semester": "4",
  "period": "integral"
}

### DELETE deleta o studying pelo id
GET {{apiurl}}/1 HTTP/1.1
Content-Type: application/json